openapi: 3.0.0
info:
  title: ""
  description: ""
  version: 0.0.1
servers:
  - url: http://localhost:3000
tags:
  - name: user
    description: ""
components:
  schemas: {}
  parameters: {}
paths:
  /users:
    get:
      tags:
        - users
      responses:
        "200":
          description: user response
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: number
                  name:
                    type: string
                  age:
                    type: number
                required:
                  - id
                  - name
                  - age
                example:
                  id: 1
                  name: ""
                  age: 20
